### ISSUE TITLE
Need a way to import repo keys.

### ISSUE THREAD

**Issue by vijayviji** [dokku-community/dokku-apt#12]
Basically, I'm trying to use dokku-apt to run the commands mentioned in script - https://get.docker.com/ubuntu/

It requires repo keys to be imported. Seems dokku-apt doesn't have a way to use repo keys.

**Comment by silvant** [comment]
It might be a little bit hacky, but importing the key in apt-env seems to 'work'

**Comment by josegonzalez** [comment]
Okay this should be relatively easy to add support for. I'll do it in the next minor.
