### ISSUE TITLE
Provide way to configure APT

### ISSUE THREAD

**Issue by esantoro** [dokku-community/dokku-apt#13]
In many cases, recommended packages are not needed in a container.

For example, I have the texlive/latex distribution in one of my project but I have to wait every time for apt to download documentation packages.

For example, I think you should implement something like a apt-config file that would then be copied in `/etc/apt/preferences.d/90dokku-customizations`.

For example, in my case the content would be:

```
APT {
  Install-Recommends "false";
}
```

Thanks for your attention.

**Comment by jazzzz** [comment]
Interesting, I will try to implement it as soon as I can.

**Comment by esantoro** [comment]
Thanks :)
