### ISSUE TITLE
install PPA before package

### ISSUE THREAD

**Issue by cromulus** [dokku-community/dokku-apt#19]
I am trying to install nightly `rustc`, and using this PPA: `ppa:infinity0/rust-nightly`
However, with an apt-repository file that reads: 
`ppa:infinity0/rust-nightly`

and an apt-packages file that reads:
`rustc`

`git push dokku master` fails with this error:
`remote: E: Unable to locate package rustc`

Any ideas?

**Comment by cromulus** [comment]
Read through the code. Seems like that's what's supposed to happen. Perhaps this is an issue with this particular PPA?

Unclear what the problem is, but I'm having this issue.

**Comment by jazzzz** [comment]
Has the MR #20 fixed this issue?

**Comment by josegonzalez** [comment]
Seems like this works now. If it doesn't, feel free to create a new issue :)
