### ISSUE TITLE
Cache installed packages between builds for a speedup

### ISSUE THREAD

**Issue by Tyilo** [dokku-community/dokku-apt#23]
I don't know if this is actually possible in a dokku plugin, but it would be nice if dokku-apt didn't have to reinstall every package every time you push to dokku.

**Comment by jalcine** [comment]
This would require copying out all of the apt-y stuff into a volume or some middle space and then adding it back in on build.

**Comment by jazzzz** [comment]
I would love to, but it seems hard to do.

**Comment by jalcine** [comment]
Yeah. A temporary (but aggressive depending on your environment) fix to use would be using Docker and keeping the package installation step _high_ in the build order.

**Comment by josegonzalez** [comment]
One thing I'd like to do in the future is allow customizing the `DOKKU_IMAGE` for a given app. We would do this during `post-extract`, and get a hash of all the apt-related files and use that as a custom image tag. If that custom tag doesn't exist on the base `DOKKU_IMAGE`, we'd create it and then use that for future building. In this way, we'd only run apt commands when the files are changed, so it would usually be a no-op.

We could probably even build a dockerfile based no DOKKU_IMAGE and run it all there. Would be super-pro :)

**Comment by josegonzalez** [comment]
To utilize the enhanced cache mechanism, please upgrade to Dokku 0.18.x.
