### ISSUE TITLE
Transfer project to dokku-community

### ISSUE THREAD

**Issue by josegonzalez** [dokku-community/dokku-apt#28]
Hi! The `dokku-apt` project is a really nice plugin, and a ton of Dokku users install it in their setup. I'd love to be able to transfer the project to the dokku-community org so that we can give it a bit more love and support :)

Thoughts on this? We would give anyone from the F4-group complete access to the code if you wish to continue maintaining it as well :)

**Comment by jazzzz** [comment]
Great idea! Do you just need us to transfer the repository ownership?

**Comment by josegonzalez** [comment]
Yeah so basically I'd need the username of someone who has admin access on this repository. I'll add them as org-admin to `dokku-community`, and then we can do the transfer (F4-Group would initiate). Once it's been accepted on my end, I would create a new group for managing the repo in dokku-community that would include anyone you think should be there.

**Comment by jazzzz** [comment]
I am admin of this repository, I will do the transfer as soon as I have the permission.
We do not need to have any permission to the transferred repository, we already do not have enough time to maintain this one!

**Comment by josegonzalez** [comment]
Visit https://github.com/dokku-community to accept the invitation!

**Comment by jazzzz** [comment]
Done. I leave you change the URLs in the doc.
