### ISSUE TITLE
Unable to build app due to deb installation error

### ISSUE THREAD

**Issue by BoluwajiDavids** [dokku-community/dokku-apt#51]
We are currently unable to deploy updates or fixes to our production server due to a deb error in the build process. This happens whether we are doing a local deployment to the server via git (ssh) or we simply rebuild the app with dokku ps:rebuild app_name.

We have attempted to update apt packages with sudo apt update and then sudo apt upgrade. This did not resolve the issue.

The error displayed is reproduced below:
```
       Reading package lists...
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
-----> Installing *.deb
dpkg-deb: error: failed to read archive '/cache/apt/cache/archives/*.deb': No such file or directory
 !     Failure during app build
 !     Retagging old image fb212186be8d as dokku/mtp-prod:latest
 !     App build failed
 !     W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
dpkg-deb: error: failed to read archive '/cache/apt/cache/archives/*.deb': No such file or directory
 !     Failure during app build
 !     Retagging old image fb212186be8d as dokku/app_name:latest
 !     App build failed
 ```
 

Note that deployment works fine on the same server previously and we made no recent changes to the server.

**Comment by josegonzalez** [comment]
Can you include the information we ask for in the [official Dokku issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems.

Additionally, include the entire deploy output, as well as the output of `ls -lah` in the root directory of your codebase. Finally, if you have any of the [files used by this plugin](https://github.com/dokku-community/dokku-apt?tab=readme-ov-file#usage), please include their contents.

Thanks!

**Comment by BoluwajiDavids** [comment]
Hi @josegonzalez 
Please see the output of dokku report mtp-prod in the txt file attached
[DokkuReportApp_name.txt](https://github.com/dokku-community/dokku-apt/files/14736191/DokkuReportApp_name.txt)

This is the complete output of the build failure when running dokku ps:rebuild mtp-prod:
-----> Cleaning up...
-----> Building mtp-prod from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs php
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-apt.git
=====> Detected Framework: Apt
-----> Reusing cache
-----> Updating apt caches
       Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
       Hit:2 http://archive.ubuntu.com/ubuntu jammy-security InRelease
       Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
       Hit:4 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
       Reading package lists...
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
-----> Installing *.deb
dpkg-deb: error: failed to read archive '/cache/apt/cache/archives/*.deb': No such file or directory
 !     Failure during app build
 !     Retagging old image fb212186be8d as dokku/mtp-prod:latest
 !     App build failed
 !     W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
dpkg-deb: error: failed to read archive '/cache/apt/cache/archives/*.deb': No such file or directory
 !     Failure during app build
 !     Retagging old image fb212186be8d as dokku/mtp-prod:latest
 !     App build failed


This also the output of ls -lah:
total 100K
drwxr-xr-x 11 dokku dokku 4.0K Mar 24 17:08 .
drwxr-xr-x 20 dokku dokku 4.0K Feb 20 16:11 ..
-rw-rw-r--  1 dokku dokku   65 Mar 23 15:56 CONTAINER.web.1
-rw-rw-r--  1 dokku dokku   65 Mar 23 15:56 CONTAINER.worker.1
-rw-------  1 dokku dokku   24 Feb 19 16:14 DOCKER_OPTIONS_DEPLOY
-rw-------  1 dokku dokku 1.5K Mar 24 17:08 ENV
-rw-rw-r--  1 dokku dokku   23 Feb 19 13:10 HEAD
-rw-rw-r--  1 dokku dokku   10 Mar 24 13:31 IP.web.1
-rw-rw-r--  1 dokku dokku   10 Mar 24 13:31 IP.worker.1
-rw-rw-r--  1 dokku dokku    4 Mar 23 15:56 PORT.web.1
-rw-rw-r--  1 dokku dokku    4 Mar 22 09:01 PORT.worker.1
-rw-rw-r--  1 dokku dokku  112 Mar 22 09:01 URLS
-rw-rw-r--  1 dokku dokku   22 Feb 19 13:12 VHOST
drwxrwxr-x  2 dokku dokku 4.0K Feb 19 13:10 branches
drwxrwxr-x  8 dokku 32767 4.0K Mar  8 12:31 cache
-rw-rw-r--  1 dokku dokku   66 Feb 19 13:10 config
-rw-rw-r--  1 dokku dokku   73 Feb 19 13:10 description
drwxrwxr-x  2 dokku dokku 4.0K Feb 19 13:10 hooks
drwxrwxr-x  2 dokku dokku 4.0K Feb 19 13:10 info
drwxrwxr-x  4 dokku dokku 4.0K Feb 19 13:13 letsencrypt
-rw-------  1 dokku dokku 2.6K Mar 24 13:31 nginx.conf
drwxrwxr-x  2 dokku dokku 4.0K Feb 20 11:43 nginx.conf.d
drwxrwxr-x 89 dokku dokku 4.0K Mar 24 16:59 objects
drwxrwxr-x  4 dokku dokku 4.0K Feb 19 13:10 refs
drwxr-x---  2 dokku dokku 4.0K Feb 20 11:43 tls


The app is a laravel app using heroku build packs. The content of both Dockerfile and Procfile are as follows:

Dockerfile:

FROM ubuntu:22.04

LABEL maintainer="Taylor Otwell"

ARG WWWGROUP
ARG NODE_VERSION=18
ARG POSTGRES_VERSION=15

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 dnsutils librsvg2-bin fswatch \
    && curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c' | gpg --dearmor | tee /etc/apt/keyrings/ppa_ondrej_php.gpg > /dev/null \
    && echo "deb [signed-by=/etc/apt/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
    && apt-get update \
    && apt-get install -y php8.2-cli php8.2-dev \
       php8.2-pgsql php8.2-sqlite3 php8.2-gd php8.2-imagick \
       php8.2-curl \
       php8.2-imap php8.2-mysql php8.2-mbstring \
       php8.2-xml php8.2-zip php8.2-bcmath php8.2-soap \
       php8.2-intl php8.2-readline \
       php8.2-ldap \
       php8.2-msgpack php8.2-igbinary php8.2-redis php8.2-swoole \
       php8.2-memcached php8.2-pcov php8.2-xdebug \
    && curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \
    && curl -sLS https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && npm install -g pnpm \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /etc/apt/keyrings/yarn.gpg >/dev/null \
    && echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/keyrings/pgdg.gpg >/dev/null \
    && echo "deb [signed-by=/etc/apt/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y yarn \
    && apt-get install -y mysql-client \
    && apt-get install -y postgresql-client-$POSTGRES_VERSION \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.2

RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail

COPY start-container /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY php.ini /etc/php/8.2/cli/conf.d/99-sail.ini
RUN chmod +x /usr/local/bin/start-container

EXPOSE 8000

ENTRYPOINT ["start-container"]



Procfile:
web: vendor/bin/heroku-php-apache2 public/
worker: php artisan queue:work --daemon

Please let me know if you require any additional information

**Comment by josegonzalez** [comment]
@BoluwajiDavids run `ls -lah` in your app repo (the one you are pushing from), not on the dokku server.

Also, do you have a `.buildpacks` file in your repo?

**Comment by BoluwajiDavids** [comment]
Hi @josegonzalez 
This is the output from ls-lah on my local machine:
total 568K
drwxr-xr-x 16 bd 4.0K Mar 24 18:01  .
drwxr-xr-x 10 boluwaji root     4.0K Aug 24  2023  ..
-rw-r--r--  1 bd  208 Jan 30 12:04  .buildpacks
-rw-r--r--  1 bd  258 Aug 10  2023  .editorconfig
-rw-r--r--  1 bd 2.2K Feb 22 16:13  .env
-rw-r--r--  1 bd 1.1K Oct  7 16:33  .env.example
drwxr-xr-x  8 bd 4.0K Mar 24 17:56  .git
-rw-r--r--  1 bd  186 Aug 10  2023  .gitattributes
-rw-r--r--  1 bd  243 Aug 10  2023  .gitignore
-rw-r--r--  1 bd    0 Feb 20 16:07  Aptfile
-rw-r--r--  1 bd   82 Jan 30 12:04  Procfile
-rw-r--r--  1 bd 4.1K Aug 10  2023  README.md
drwxr-xr-x  8 bd 4.0K Jan 30 12:04  app
-rw-r--r--  1 bd  127 Jan 30 12:04  app.json
-rwxr-xr-x  1 bd 1.7K Aug 10  2023  artisan
drwxr-xr-x  3 bd 4.0K Aug 10  2023  bootstrap
-rw-r--r--  1 bd 2.2K Jan 30 12:04  composer.json
-rw-r--r--  1 bd 398K Jan 30 12:04  composer.lock
drwxr-xr-x  2 bd 4.0K Jan 30 12:04  config
drwxr-xr-x  5 bd 4.0K Aug 10  2023  database
drwxr-xr-x  7 bd 4.0K Aug 19  2023  docker
-rw-r--r--  1 bd  817 Jan 30 12:04  docker-compose.yml
drwxr-xr-x  2 bd 4.0K Jan 30 12:04  dokku
drwxr-xr-x 36 bd 4.0K Aug 19  2023  node_modules
-rw-r--r--  1 bd  32K Aug 19  2023  package-lock.json
-rw-r--r--  1 bd  271 Aug 19  2023  package.json
-rw-r--r--  1 bd 1014 Aug 18  2023  phpunit.xml
drwxr-xr-x  3 bd 4.0K Jan 30 12:04  public
drwxr-xr-x  5 bd 4.0K Aug 10  2023  resources
drwxr-xr-x  2 bd 4.0K Feb 19 12:20  routes
drwxr-xr-x  5 bd 4.0K Aug 10  2023  storage
drwxr-xr-x  4 bd 4.0K Aug 10  2023  tests
drwxr-xr-x 60 bd 4.0K Nov 30 08:45  vendor
-rw-r--r--  1 bd  263 Aug 10  2023  vite.config.js

This is the also the content of the .buildpacks:

https://github.com/heroku/heroku-buildpack-apt.git
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-php.git
https://github.com/heroku/heroku-buildpack-nginx.git

**Comment by BoluwajiDavids** [comment]
Also just curious about what changed?
Everything worked fine before. We made no changes on the server and no build related change to the code base. Why did the build and deployment stopped all of a sudden?

**Comment by BoluwajiDavids** [comment]
Yes I did that and it works now, thanks.
But why did it stop working? Deployment worked fine even with the apt buildpack present before. As mentioned, nothing changed on our end.

**Comment by josegonzalez** [comment]
Probably changes upstream in that apt buildpack. [Here is a commit](https://github.com/heroku/heroku-buildpack-apt/commit/f03630fd3e97842fe4ba789711ff3bba22daf8b6) that does shell-hardening, which probably makes no-op usage a bug.
